Repository LLNL/hiop, pull requests merged in 2020-12, with the labels that each got.

#125 Removing RAJA from github actions build
  .github/workflows/test.yml
Labels: bug, testing/continuous integration

#137 Fix Github Actions CI
  .github/workflows/test.yml
Labels: bug, testing/continuous integration

#148 Adding version info struct
  CMakeLists.txt
  src/Interface/hiopVersion.hpp
  src/Interface/hiop_defs.hpp.in
Labels: documentation, enhancement

#146 Full build matrix dev
  .gitlab-ci.yml
  BUILD.sh
  CMakeLists.txt
  README_developers.md
  cmake/FindValgrind.cmake
  doc/src_usermanual/techrep_main.tex
  scripts/.ascentVariables.sh.swp
  scripts/ascentVariables.sh
  scripts/defaultBuild.sh
  scripts/fullBuildMatrix.sh
  scripts/marianasVariables.sh
  scripts/newellVariables.sh
Labels: enhancement, testing/continuous integration

#141 Vector Tests Consolidation
  tests/LinAlg/vectorTests.hpp
  tests/LinAlg/vectorTestsPar.cpp
  tests/LinAlg/vectorTestsPar.hpp
  tests/LinAlg/vectorTestsRajaPar.cpp
  tests/LinAlg/vectorTestsRajaPar.hpp
  tests/testVector.cpp
Labels: enhancement, testing/continuous integration

#166 Use HiOp option to change the mode of STRUMP, and fix bugs/typos.
  src/LinAlg/hiopLinSolverSparseSTRUMPACK.cpp
  src/Optimization/hiopAlgFilterIPM.cpp
  src/Optimization/hiopIterate.cpp
  src/Optimization/hiopIterate.hpp
  src/Optimization/hiopKKTLinSys.cpp
  src/Utils/hiopOptions.cpp
Labels: bug

#169 Magma 2.5.4 CI integration
  BUILD.sh
Labels: build system
