Repository LLNL/hiop, pull requests merged in 2021-07, with the labels that each got.

#259 RAJA implementation for sparse matrix
  src/LinAlg/hiopLinAlgFactory.hpp
  src/LinAlg/hiopMatrixRajaSparseTriplet.cpp
  src/LinAlg/hiopMatrixRajaSparseTriplet.hpp
  src/LinAlg/hiopMatrixSparse.hpp
  src/LinAlg/hiopMatrixSparseTriplet.hpp
  src/LinAlg/hiopVectorInt.hpp
  src/LinAlg/hiopVectorIntRaja.cpp
  src/LinAlg/hiopVectorIntRaja.hpp
  src/LinAlg/hiopVectorIntSeq.cpp
  src/LinAlg/hiopVectorIntSeq.hpp
  tests/LinAlg/matrixTestsRajaSparseTriplet.cpp
  tests/LinAlg/matrixTestsRajaSparseTriplet.hpp
  tests/LinAlg/matrixTestsSparse.hpp
  tests/LinAlg/matrixTestsSparseTriplet.cpp
  tests/LinAlg/matrixTestsSparseTriplet.hpp
  tests/LinAlg/matrixTestsSymSparseTriplet.hpp
  tests/LinAlg/vectorTestsInt.hpp
  tests/testMatrixSparse.cpp
  tests/testVector.cpp
Labels: enhancement

#282 Update umpire version to 5.0.1
  scripts/ascentVariables.sh
  scripts/marianasVariables.sh
  scripts/newellVariables.sh
Labels: build system

#279 Options & logger for PriDec solver
  doc/hiop_usermanual.pdf
  doc/src_usermanual/techrep_main.tex
  src/Drivers/nlpPriDec_ex8.cpp
  src/Drivers/nlpPriDec_ex8.hpp
  src/Drivers/nlpPriDec_ex8_driver.cpp
  src/Drivers/nlpPriDec_ex9.cpp
  src/Drivers/nlpPriDec_ex9.hpp
  src/Interface/hiopInterfacePrimalDecomp.cpp
  src/Interface/hiopInterfacePrimalDecomp.hpp
  src/Optimization/hiopAlgFilterIPM.cpp
  src/Optimization/hiopAlgPrimalDecomp.cpp
  src/Optimization/hiopAlgPrimalDecomp.hpp
  src/Optimization/hiopNlpFormulation.cpp
  src/Utils/hiopLogger.cpp
  src/Utils/hiopLogger.hpp
  src/Utils/hiopOptions.cpp
  src/Utils/hiopOptions.hpp
  tests/testMatrixSparse.cpp
  tests/testMatrixSymSparse.cpp
Labels: documentation, enhancement, solver options
