Repository LLNL/hiop, pull requests merged in 2021-08, with the labels that each got.

#290 Fix the feasibility problem in MDS format
  src/Optimization/hiopAlgFilterIPM.cpp
  src/Optimization/hiopFRProb.cpp
  src/Utils/hiopOptions.cpp
Labels: bug, enhancement

#291 add user options to control the max/min constraint violation used in the filter line-search algorithm
  src/Optimization/hiopAlgFilterIPM.cpp
  src/Optimization/hiopAlgFilterIPM.hpp
  src/Utils/hiopOptions.cpp
Labels: solver options

#294 update HiOp's Magma solvers to v2.6.1
  scripts/ascentVariables.sh
  scripts/marianasVariables.sh
  scripts/newellVariables.sh
  src/Drivers/nlpMDS_ex4_driver.cpp
  src/LinAlg/hiopLinSolverIndefDenseMagma.cpp
  src/LinAlg/hiopLinSolverIndefDenseMagma.hpp
Labels: profiling/optimization, porting

#301 Sparse gpu kernel dev 1
  src/LinAlg/hiopMatrixRajaSparseTriplet.cpp
  src/LinAlg/hiopMatrixRajaSparseTriplet.hpp
  src/LinAlg/hiopMatrixSparse.hpp
  src/LinAlg/hiopMatrixSparseTriplet.hpp
  src/LinAlg/hiopVectorInt.hpp
  src/LinAlg/hiopVectorIntRaja.cpp
  src/LinAlg/hiopVectorIntRaja.hpp
  src/LinAlg/hiopVectorIntSeq.cpp
  src/LinAlg/hiopVectorIntSeq.hpp
  tests/LinAlg/matrixTestsRajaSparseTriplet.cpp
  tests/LinAlg/matrixTestsRajaSparseTriplet.hpp
  tests/LinAlg/matrixTestsSparse.hpp
  tests/LinAlg/matrixTestsSparseTriplet.cpp
  tests/LinAlg/matrixTestsSparseTriplet.hpp
  tests/LinAlg/matrixTestsSymSparseTriplet.hpp
  tests/LinAlg/vectorTestsInt.hpp
  tests/testMatrixSparse.cpp
  tests/testVector.cpp
Labels: enhancement
